import { GoogleGenAI } from "@google/genai";
import { AI_CONFIG } from "../../config/ai.config";



function getAIClient() {
  const apiKey = process.env.GOOGLE_GENAI_API_KEY;

  if (!apiKey) {
    throw new Error(
      "GOOGLE_GENAI_API_KEY is not defined in environment variables."
    );
  }

  return new GoogleGenAI({ apiKey });
}

import wav from "wav";

interface GeneratedAudio {
  buffer: Buffer;
  mimeType: string;
}

export const generate_text_audio = async (
  textFormQuestion: string
): Promise<GeneratedAudio> => {
  const ai = getAIClient();

  try {
    const response = await ai.models.generateContent({
      model: AI_CONFIG.TTS_MODEL,

      contents: [
        {
          parts: [
            {
              text: textFormQuestion,
            },
          ],
        },
      ],

      config: {
        responseModalities: ["AUDIO"],

        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: "Kore",
            },
          },
        },
      },
    });

    const inlineData =
      response.candidates?.[0]?.content?.parts?.[0]?.inlineData;

    const audioData = inlineData?.data;

    if (!audioData) {
      throw new Error("No audio generated by Gemini TTS");
    }

    // Gemini TTS gives us raw PCM audio
    const pcmBuffer = Buffer.from(audioData, "base64");

    // Convert PCM → WAV
    const wavBuffer = await new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];

      const writer = new wav.Writer({
        sampleRate: 24000,
        channels: 1,
        bitDepth: 16,
      });

      writer.on("data", (chunk: Buffer) => {
        chunks.push(chunk);
      });

      writer.on("finish", () => {
        resolve(Buffer.concat(chunks));
      });

      writer.on("error", reject);

      writer.end(pcmBuffer);
    });

    return {
      buffer: wavBuffer,
      mimeType: "audio/wav",
    };

  } catch (err) {
    console.error("Gemini TTS Error:", err);
    throw err;
  }
};

export const generate_audio_text = async (
  audioBuffer: Buffer,
  mimeType: string
): Promise<string> => {
  const ai = getAIClient();

  try {
    const response = await ai.models.generateContent({
      model: AI_CONFIG.DEFAULT_MODEL,

      contents: [
        {
          parts: [
            {
              inlineData: {
                mimeType: mimeType,
                data: audioBuffer.toString("base64"),
              },
            },
            {
              text: `
Transcribe the user's speech exactly into text.

Rules:
- Return ONLY the transcription.
- Do not explain anything.
- Do not summarize.
- Do not add information.
- Preserve the meaning of what the user said.
              `,
            },
          ],
        },
      ],
    });

    const transcript = response.text?.trim();

    if (!transcript) {
      throw new Error("Failed to transcribe audio");
    }

    return transcript;

  } catch (error) {
    console.error("Audio transcription error:", error);
    throw error;
  }
};

export const evaluateMockAnswer = async (
  question: string,
  answer: string
): Promise<any> => {
  const ai = getAIClient();

  const prompt = `
You are an expert technical interviewer.

Interview Question:
${question}

Candidate's Answer:
${answer}

Evaluate the candidate's answer to the given interview question.

Give:
- score from 0 to 10
- technical correctness
- quality of the answer
- short feedback

Return ONLY valid JSON in this format:

{
  "score": 0,
  "technicalCorrectness": "",
  "feedback": ""
}
`;

  try {
    const response = await ai.models.generateContent({
      model: AI_CONFIG.DEFAULT_MODEL,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text || "{}";

    return JSON.parse(text);

  } catch (error) {
    console.error("Mock answer evaluation error:", error);
    throw error;
  }
};
